import robotjs from 'robotjs';
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
// TODO: NEVER DO A GIT PUSH WITH THE ENCRYPTED PASSWORD VARIABLE
const emailOrUsername = 'Dr4kk0nnys';
const encryptedPassword = 'd2h5X3lvdV9sb29raW5nX2ludG9fdGhpc18';
setTimeout(() => {
    robotjs.typeString(emailOrUsername);
    robotjs.keyTap('enter');
    robotjs.typeString(Buffer.from(encryptedPassword, 'base64').toString('ascii'));
    robotjs.keyTap('enter');
}, 4000);
